### ISSUE TITLE
cant upload 

### ISSUE THREAD

**Issue by heliawins** [Roblox/roblox-blender-plugin#33]
if i upload my module something about error of python trace back (most resent call last):
file c:users/user/appdata/roaming/blender foundation/blender/4.0/scripts/addons/roblox-blender-plugin/lib/get_selected_objects.py",line 66, in get_selected_objects for selected_objects in context.selected_ids:
attributerror: 'context' object has no attribute 'selected_ids'. did you mean 'selected_bones'?

that's the error I'm getting pls help

**Comment by Babanimus** [comment]
I have the same issue

**Comment by EngyneMac** [comment]
Solution:

https://github.com/Roblox/roblox-blender-plugin/issues/32#issuecomment-1816527799

**Comment by othomson-roblox** [comment]
Thanks for flagging! This plugin did not work with Blender 4.0 but this issue has been resolved in the latest release:

https://github.com/Roblox/roblox-blender-plugin/releases/tag/v1.0.2
